### ISSUE TITLE
Tracking issue for number constants 

### ISSUE THREAD

**Issue by barbariand** [barbariand/Reti#27]
Tracking issue for all numerical constants that are planned or added to Reti as of the date of the latest update.
This issue is not to be closed and if you want to add more please refrence  this tracking issue

- [x] f64limitations
  - [x] ∞ Infinity
  - [x] -∞ Negative Infinity
  - [x] N/A Max representable
  - [x] N/A min representable
 
- [ ] Mathematical constants
  - [x] e - Eulers number
  - [x] ln(2) - Natural log of 2
  - [x] π - Pi
  - [x] √2 - sqrt(2)
  - [ ] √3 - sqrt(3)
  - [x] τ - tau=2π
  - [x] φ - Phi the golden ratio
  - [x] γ - Euler-Mascheroni constant
  - [ ] Other
 
- [ ] Physics SI Units
  - [x] c - Speed of light
  - [x] h - Planks constant
  - [x] G - Gravitational constant
  - [x] m_e - Mass of electron
  - [x] m_m - Mass of muon
  - [x] m_t - Mass of tau
  - [x] m_p - Mass of proton
  - [x] m_n - Mass of neutron
  - [x] g- gravitation
    - [x] Standard definition - 9.80665
    - [x] Equator - 9.780_367_711_5
    - [x] Sweden - 9.82
    - [x] USA - 9.80
    - [x] 9.78
    - [x] 9.79
    - [x] 9.80
    - [x] 9.81
    - [x] 9.82
    - [x] 9.83
    - [x] Simple - 10.0
  - [ ] Other

- [ ] Physics Imperial Units
  - [ ] c - Speed of light
  - [ ] h - Planks constant
  - [ ] G - Gravitational constant
  - [ ] m_e - Mass of electron
  - [ ] m_m - Mass of muon
  - [ ] m_t - Mass of tau
  - [ ] m_p - Mass of proton
  - [ ] m_n - Mass of neutron
  - [x] g- gravitation
    - [x] Standard definition - 32.174
    - [x] Equator - 32.0876863
    - [x] Sweden - 32.217
    - [x] USA - 32.1522
    - [x] 32.08
    - [x] 32.12
    - [x] 32.15
    - [x] 32.18
    - [x] 32.21
    - [x] 32.25
    - [x] Simple - 32.15?
  - [ ] Other

- [ ] Chem
  - [x] N_A - Avogrados konstant
  - [ ] Other

If there is any more that are needed then i can add them here to the list

**Comment by Alvinn8** [comment]
Imperial?!? Honestly I don't think we should have those. Physics is basically always done with metric units, and the meaning of the constants should be metric in my opinion.

**Comment by Alvinn8** [comment]
I don't think we should add \pm\infty nor NaN as constants. While they may exist in f64:s, mathematically they are not real numbers and shouldn't be something that we represent in Reti like that. In some cases, like if we add sets `[0, \infty)` I think that should be handled separately. I also don't think f64 min/max is relevant from a mathematical perspective.

**Comment by Alvinn8** [comment]
ln(2), \sqrt{2}, \sqrt{3} don't need to be constants, to get them you just have to type what I just did and evaluate the sqrt or ln.

**Comment by barbariand** [comment]
> Imperial?!? Honestly I don't think we should have those. Physics is basically always done with metric units, and the meaning of the constants should be metric in my opinion.

I know that they are rarley used in sweden but i think they are used enought from people in usa that it would be worth it as i have macros to make it really easy to convert

**Comment by barbariand** [comment]
> I don't think we should add \pm\infty nor NaN as constants. While they may exist in f64:s, mathematically they are not real numbers and shouldn't be something that we represent in Reti like that. In some cases, like if we add sets `[0, \infty)` I think that should be handled separately. I also don't think f64 min/max is relevant from a mathematical perspective.

i can agree with max and min buuut i think infinity is actually nice sometimes,  but yea maybe it should be evaluated seperatly

**Comment by barbariand** [comment]
> ln(2), \sqrt{2}, \sqrt{3} don't need to be constants, to get them you just have to type what I just did and evaluate the sqrt or ln.

Yea but if we where gonna substitute sin(π)=0 then i think it is ok too have and do that substitution too, remeber that as we are working with presison it is not actually garantied to be the same even during the same run of the program and it would be kinda wierd if it changed. Now ik there needs to be a limit somewhere

**Comment by barbariand** [comment]
It is also not that hard to suport imperial , except maybe in a ui design perspective but even that is not that big of a hurdel

**Comment by barbariand** [comment]
> > ln(2), \sqrt{2}, \sqrt{3} don't need to be constants, to get them you just have to type what I just did and evaluate the sqrt or ln.
> 
> Yea but if we where gonna substitute sin(π)=0 then i think it is ok too have and do that substitution too, remeber that as we are working with presison it is not actually garantied to be the same even during the same run of the program and it would be kinda wierd if it changed. Now ik there needs to be a limit somewhere

Maybe it is there we should draw the line and don't repeat our self, I will sleep on this.

**Comment by barbariand** [comment]
Though if it is a mathident we can maybe do ast magic hmmm

**Comment by barbariand** [comment]
Lol Ive not even thought about it but we need to do conditional ast manipulation depending on what constants are actually correct

**Comment by Alvinn8** [comment]
> Lol Ive not even thought about it but we need to do conditional ast manipulation depending on what constants are actually correct

What do you mean?

**Comment by barbariand** [comment]
If sin is redefined we can not assumme that sin(x)^2+cos(x)^2 =1 or derivatiok and sutch also breaks

**Comment by Alvinn8** [comment]
I kinda think that constants should be `MathExpr`s. So that `m_e=9.1\cdot10^{-31}`. Because with the correct setup in the `constants` branch I don't even think f64:s can support such small numbers, so it might just be equal to zero.

Long term I also kind of want all our evaluations to be handled in simplification, with infinite prediction using fractions and constants. Only when approximating  would we be forced to used f64:s or similar.

**Comment by barbariand** [comment]
Yea ok that is actually a better idea tbh

**Comment by Alvinn8** [comment]
While American users might want to think about the speed of light in imperial units, the constant `c` is associated with the value 299 ... in meters/second. You can measure the speed of light in miles/s if you want, but the constant c, that's still a constant in meters/second.

If we want to support imperial units I would rather see a proper units system where you can change units on the result, so all calculations could be in SI units and the result is "32 m/s", and when pressing a button to change units it will translate the value to "10 feet/s" or whatever is relevant. But I also think this is hard and may be error-prone. So if implemented it should be done in the future in my opinion.

**Comment by barbariand** [comment]
So pi and sutch are not used untill approximating

**Comment by barbariand** [comment]
> While American users might want to think about the speed of light in imperial units, the constant `c` is associated with the value 299 ... in meters/second. You can measure the speed of light in miles/s if you want, but the constant c, that's still a constant in meters/second.
> 
> If we want to support imperial units I would rather see a proper units system where you can change units on the result, so all calculations could be in SI units and the result is "32 m/s", and when pressing a button to change units it will translate the value to "10 feet/s" or whatever is relevant. But I also think this is hard and may be error-prone. So if implemented it should be done in the future in my opinion.

I'd rather see us have this than the constants but if we do actually unit calculation I think it should be removed and that everything should flow through the SI system. But to be clear I don't need to keep the Imperial i just slightly think we should

**Comment by barbariand** [comment]
The pros outwey the cons from how I see it for having imperial constants that are pre converted when we can't but ig you could do it lanualy

**Comment by Alvinn8** [comment]
> So pi and sutch [sic] are not used untill [sic] approximating

Yes exactly. Just like a mathematician would prefer to answer `=2\pi/3+\sqrt{2}` instead of `/approx8.2...` I think Reti should do the same

**Comment by barbariand** [comment]
And that makes it easier to do complex numbers too huh
